name: Gradle build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'zulu'
        
    - name: Build with Gradle
      run: ./gradlew clean build
